import AutoStoriesOutlinedIcon from "@mui/icons-material/AutoStoriesOutlined";
import RefreshOutlinedIcon from "@mui/icons-material/RefreshOutlined";
import {
  Alert,
  Button,
  Card,
  CardContent,
  CircularProgress,
  Stack,
  Typography,
} from "@mui/material";
import { useQuery } from "@tanstack/react-query";

import { listProcessingRuns } from "../../../api/queue";
import type { EnrichmentListEntryFile, ScopeDescribeRequest } from "../../../api/types";
import { useEnrichmentJob } from "../../../hooks/useEnrichmentJob";
import { useScopeEnrichmentPayload } from "../../../hooks/useScopeEnrichmentPayload";
import { useScopeEnrichments } from "../../../hooks/useScopeEnrichments";
import { EnrichmentArtifactView } from "./EnrichmentArtifactView";


export function ScopeWikiPanel({
  scope,
  title,
}: {
  scope: ScopeDescribeRequest;
  title: string;
}) {
  const enrichmentJob = useEnrichmentJob();
  const enrichments = useScopeEnrichments(scope);
  const runs = useQuery({
    queryKey: ["processing-runs"],
    queryFn: listProcessingRuns,
    refetchInterval: (query) => query.state.data?.runs.some(
      (run) => ["queued", "pending", "running"].includes(run.status),
    ) ? 1_200 : 10_000,
  });

  const wikiEntry = (enrichments.data?.enrichments ?? []).find(
    (entry): entry is EnrichmentListEntryFile =>
      entry.kind === "file" && entry.name === "wiki--llm_wiki.json",
  );
  const wiki = useScopeEnrichmentPayload(scope, wikiEntry?.name ?? "", Boolean(wikiEntry));
  const runId = enrichmentJob.data?.run_id;
  const run = runs.data?.runs.find((item) => item.id === runId);
  const generationActive = enrichmentJob.isPending || ["queued", "pending", "running"].includes(run?.status ?? "");
  const generationFailed = run?.status === "error";

  const generate = () => enrichmentJob.mutate({
    enricher_name: "llm_wiki",
    scope,
    enricher_config: { title: `${title} Wiki` },
  });

  return (
    <Card variant="outlined">
      <CardContent>
        <Stack spacing={2}>
          <Stack
            direction={{ xs: "column", sm: "row" }}
            justifyContent="space-between"
            alignItems={{ xs: "flex-start", sm: "center" }}
            spacing={1.5}
          >
            <Stack spacing={0.25}>
              <Typography variant="h6" fontWeight={700}>LLM Wiki</Typography>
              <Typography variant="body2" color="text.secondary">
                A grounded Markdown knowledge product generated by the model-backed synthesizer selected in Tools.
              </Typography>
            </Stack>
            <Button
              variant={wikiEntry ? "outlined" : "contained"}
              startIcon={wikiEntry ? <RefreshOutlinedIcon /> : <AutoStoriesOutlinedIcon />}
              onClick={generate}
              disabled={generationActive}
            >
              {generationActive ? "Generating…" : wikiEntry ? "Regenerate Wiki" : "Generate Wiki"}
            </Button>
          </Stack>

          {generationActive ? (
            <Alert icon={<CircularProgress size={18} />} severity="info">
              Ollama is building the wiki. You can leave this page; the result is saved as an enrichment artifact.
            </Alert>
          ) : null}
          {generationFailed ? (
            <Alert severity="error">
              {run?.error || run?.items?.[0]?.error || "Wiki generation failed. Check that the selected model is available in Tools."}
            </Alert>
          ) : null}
          {enrichmentJob.isError ? (
            <Alert severity="error">
              {enrichmentJob.error instanceof Error ? enrichmentJob.error.message : "Could not start wiki generation."}
            </Alert>
          ) : null}
          {enrichments.isLoading || wiki.isLoading ? <CircularProgress size={22} /> : null}
          {enrichments.isError || wiki.isError ? (
            <Alert severity="warning">The current wiki could not be loaded.</Alert>
          ) : null}
          {wiki.data ? <EnrichmentArtifactView data={wiki.data.data} /> : null}
          {!wiki.data && !enrichments.isLoading && !generationActive ? (
            <Alert severity="info">
              No LLM wiki has been generated for this {scope.scope_type} yet.
            </Alert>
          ) : null}
        </Stack>
      </CardContent>
    </Card>
  );
}
