"""Public Processor API contracts and helpers, included with OSII."""

from .client import ProcessorClient, ProcessorClientError
from .models import (
    Artifact,
    Capability,
    DocumentInput,
    EmbeddingInput,
    EmbeddingRequest,
    EmbeddingResponse,
    EmbeddingVector,
    EnrichmentRequest,
    EnrichmentResponse,
    Entity,
    EntityListArtifactData,
    ExtractionRequest,
    ExtractionResponse,
    KnowledgeGraphArtifactData,
    KnowledgeGraphEdge,
    KnowledgeGraphNode,
    ModelContext,
    ProvenanceRef,
    ProcessorDescriptor,
    ProcessorKind,
    ScopeInput,
    SynthesisRequest,
    SynthesisResponse,
    TableArtifactData,
    TableColumn,
    TextSegment,
    WikiMarkdownArtifactData,
)
from .service import (
    Embedder,
    Enricher,
    Extractor,
    Synthesizer,
    create_openai_processor_app,
    create_processor_app,
)

__all__ = [
    "Artifact",
    "Capability",
    "DocumentInput",
    "EmbeddingInput",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "EmbeddingVector",
    "Embedder",
    "Enricher",
    "EnrichmentRequest",
    "EnrichmentResponse",
    "Entity",
    "EntityListArtifactData",
    "ExtractionRequest",
    "ExtractionResponse",
    "Extractor",
    "KnowledgeGraphArtifactData",
    "KnowledgeGraphEdge",
    "KnowledgeGraphNode",
    "ModelContext",
    "ProcessorClient",
    "ProcessorClientError",
    "ProcessorDescriptor",
    "ProcessorKind",
    "ProvenanceRef",
    "ScopeInput",
    "SynthesisRequest",
    "SynthesisResponse",
    "Synthesizer",
    "TableArtifactData",
    "TableColumn",
    "TextSegment",
    "WikiMarkdownArtifactData",
    "create_processor_app",
    "create_openai_processor_app",
]
